language: node_js
node_js:
  - "6"

cache:
  directories:
  - node_modules
notifications:
  email:
    - sway.liang@gmail.com
script: 
  - npm run publish
  - npm run start
  - npm run lint-sync
  - npm run js-lint
